# Generated by Django 6.0.2 on 2026-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palabra_correcta",
                    models.CharField(max_length=100, verbose_name="Palabra Correcta"),
                ),
                ("frase", models.TextField(verbose_name="Frase con hueco")),
                ("nivel", models.IntegerField(default=1, verbose_name="Nivel")),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
