# Generated by Django 6.0.2 on 2026-02-17 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0002_ejercicio_creado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Curso"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "estudiantes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cursos_inscritos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_dictados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ejercicio",
            name="curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ejercicios",
                to="ejercicios.curso",
            ),
        ),
    ]
