"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$dqx9atk26uuajf8n_+zsfcw6q5%-0+9l83t(z_$=865&)ld5m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ejercicios",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('es', _('Spanish')),         # Español
    ('en', _('English')),         # Inglés
    ('zh-hans', _('Chinese')),    # Chino Simplificado
    ('hi', _('Hindi')),           # Hindi
    ('ar', _('Arabic')),          # Árabe
    ('pt', _('Portuguese')),      # Portugués
    ('fr', _('French')),          # Francés
    ('ru', _('Russian')),         # Ruso
    ('ja', _('Japanese')),        # Japonés
    ('de', _('German')),          # Alemán
    ('pa', _('Punjabi')),         # Punyabí
    ('jv', _('Javanese')),        # Javanés
    ('ko', _('Korean')),          # Coreano
    ('vi', _('Vietnamese')),      # Vietnamita
    ('te', _('Telugu')),          # Telugu
    ('mr', _('Marathi')),         # Maratí
    ('ta', _('Tamil')),           # Tamil
    ('tr', _('Turkish')),         # Turco
    ('it', _('Italian')),         # Italiano
    ('th', _('Thai')),            # Tailandés
    ('gu', _('Gujarati')),        # Guyaratí
    ('pl', _('Polish')),          # Polaco
    ('uk', _('Ukrainian')),       # Ucraniano
    ('fa', _('Persian')),         # Persa
    ('ml', _('Malayalam')),       # Malayalam
    ('kn', _('Kannada')),         # Canarés
    ('or', _('Oriya')),           # Oriya
    ('su', _('Sundanese')),       # Sundanés
    ('ro', _('Romanian')),        # Rumano
    ('az', _('Azerbaijani')),     # Azerbaiyano
]

# 📂 Carpeta donde Django guardará los archivos de traducción (.po)
LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
